print(1+1) # 2

print(2**3) #2의 3승 = 8

print(5%3) # %는 나머지를 구하는 것, 답: 2
print(10%3) # 1

print(5//3) # //는 몫을 구하는 것, 답: 1
print(6//2) # 3

print(10 > 3) # True
print(4 >= 7) # False
print(10 < 3) # False
print(5 <= 5) # True

print(1 == 2) # False
print(3 == 3) # True
print(1+2 == 3) # True
# ==는 앞 뒤가 똑같다는 뜻

print(1 != 3)
# !=는 앞이랑 뒤가 똑같지 않다는 뜻
print(not (1 != 3))

print((1 > 0) and (2 > 1)) # True  and 대신 &(SHIFT + 7)을 입력해도 됨
print((4 > 5) or (6 > 5)) # True  4 > 5가 오답이래도 6 > 5가 정답이라서. or 대신에 |을 써도 됨.
