# 애완동물을 소개해주세요
animal = "강아지"
name = "연탄이"
age = 4
hobby = "공놀이"
is_adult = age >= 3

print ("우리집 " + animal + "의 이름은 " + name + "예요")
print (name + "는 " + str(age) + "살이며, " + hobby + "를 좋아합니다")
# 정수형은 앞에 str을 붙인다

# + 말고 ,(콤마)도 사용 가능, 근데 ,가 붙으면 띄어쓰기가 하나 입력됨.
# ,를 쓸 때는 정수형 앞에 str을 안 붙여도 된다.
print ("우리집 ", animal, "의 이름은 ", name, "예요")
print (name, "는 ", age, "살이며, ", hobby, "를 좋아합니다")

# 여러 문장 드래그하고 'CTRL + /'를 입력하면 한 번에 주석처리가 된다
# 에라이
# 모르겠다
# 이게뭐냐
